CONTRIBUTING.md

docs: change CONTRIBUTING.md

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

chore: add github issue, pr template

---

frontend/src/lib/api/auth/auth.js
frontend/src/lib/api/auth/auth.test.js
frontend/src/lib/api/auth/index.js
frontend/src/modules/auth/auth.js
frontend/src/modules/auth/auth.test.js
frontend/src/modules/auth/index.js

resolved #17 
Add frontend auth module
💔Thank you!

feat: add auth module (action, reducer, saga)

---

frontend/src/component/common/Button/Button.js
frontend/src/component/common/Button/Button.test.js
frontend/src/component/common/Button/__snapshots__/Button.test.js.snap
frontend/src/component/common/Button/index.js

resolved #20  
Add components/common/Button 
💔Thank you!

feat: add common Button component

---

frontend/src/component/common/Box/Box.js
frontend/src/component/common/Box/Box.test.js
frontend/src/component/common/Box/__snapshots__/Box.test.js.snap
frontend/src/component/common/Box/index.js
frontend/src/pages/DetailPage/DetailPage.test.js
frontend/src/pages/FinalPage/FinalPage.test.js
frontend/src/pages/GroupPage/GroupPage.test.js
frontend/src/pages/RequestCallPage/RequestCallPage.test.js
frontend/src/pages/RequestPage/RequestPage.test.js
frontend/src/pages/WaitingPage/WaitingPage.test.js

feat: add common Box component

---

frontend/src/App.js
frontend/src/__snapshots__/App.test.js.snap
frontend/src/component/common/TextInput/TextInput.js
frontend/src/component/common/TextInput/TextInput.test.js
frontend/src/component/common/TextInput/__snapshots__/TextInput.test.js.snap
frontend/src/component/common/TextInput/index.js

resolved #21 
add common TextInput component
💔Thank you!

feat: add common TextInput component

---

CONTRIBUTING.md

resolved #43 
* Add backend contributing guideline
💔Thank you!

docs: add backend contributing guideline

---

frontend/package.json

test: exclude serviceWorker.js and index.js from test

---

.gitignore
frontend/src/lib/api/carpool/carpool.js
frontend/src/lib/api/carpool/carpool.test.js
frontend/src/lib/api/carpool/index.js
frontend/src/modules/carpoolRequest/carpoolRequest.js
frontend/src/modules/carpoolRequest/carpoolRequest.test.js
frontend/src/modules/carpoolRequest/index.js

feat: Add carpoolRequest module (action, reducer, saga)

---

README.md
frontend/src/modules/carpoolRequest/carpoolRequest.js

resolved #55 
add design and planning.
💔Thank you!

docs: add design and planning

---

frontend/src/lib/api/group/group.js
frontend/src/lib/api/group/group.test.js
frontend/src/lib/api/group/index.js
frontend/src/modules/carpoolRequest/carpoolRequest.js
frontend/src/modules/group/group.js
frontend/src/modules/group/group.test.js
frontend/src/modules/group/index.js

resolved #35
feat: add group module (action, reducer, saga)
💔Thank you!

feat: add group module (action, reducer, saga)

---

frontend/src/components/intro/Introduction/Introduction.js
frontend/src/components/intro/Introduction/Introduction.test.js
frontend/src/containers/IntroContainer/IntroContainer.js
frontend/src/containers/IntroContainer/IntroContainer.test.js
frontend/src/containers/IntroContainer/__snapshots__/IntroContainer.test.js.snap
frontend/src/containers/IntroContainer/index.js
frontend/src/pages/IntroPage/IntroPage.js
frontend/src/pages/IntroPage/IntroPage.test.js

resolved #45  
- [] Created tests which fail without the change (if possible)
💔Thank you!

feat:IntroPage updated

---

frontend/src/components/Request/Checkbox/Checkbox.js
frontend/src/components/Request/Checkbox/__snapshots__/Checkbox.test.js.snap
frontend/src/components/Request/Request.css
frontend/src/components/Request/Request.js
frontend/src/components/Request/__snapshots__/Request.test.js.snap
frontend/src/pages/RequestPage/__snapshots__/RequestPage.test.js.snap

feat:added some style

---

backend/common/command/tests/test_carpool_request_create_command.py
backend/common/command/tests/test_carpool_request_delete_command.py
backend/common/command/tests/test_group_create_command.py
backend/common/command/tests/test_user_create_command.py
backend/common/command/tests/test_user_login_command.py
backend/common/command/tests/test_user_logout_command.py
backend/common/command/user_login_command.py
backend/common/rpc/infra/adapter/redis/tests/test_redis_rpc_client.py
backend/common/rpc/infra/adapter/redis/tests/test_redis_rpc_server.py
backend/scripts/travis.sh

resolved #<issue-number> 
💔Thank you!

test: add command testcase

---

backend/api_gateway/group_endpoint/tests/test_group_controller.py
backend/api_gateway/group_endpoint/urls.py
backend/api_gateway/group_endpoint/views.py
backend/group_service/group/management/commands/runservice.py

resolved #118 #120  
Fixed issues relating to group_service backend
💔Thank you!

chore: group_service change create, update endpoint, chore: refactor group_service register_signal_handler

---

frontend/src/components/common/Button/Button.js
frontend/src/index.css

no issue but was necessary
fix sonarcloud bug
💔Thank you!

chore: fix sonarcloud bug

---

frontend/src/App.js
frontend/src/components/Login/Login.js
frontend/src/components/Login/Login.test.js
frontend/src/components/Login/__snapshots__/Login.test.js.snap
frontend/src/components/Login/index.js
frontend/src/containers/LoginContainer/LoginContainer.js
frontend/src/containers/LoginContainer/LoginContainer.test.js
frontend/src/containers/LoginContainer/__snapshots__/LoginContainer.test.js.snap
frontend/src/containers/LoginContainer/index.js
frontend/src/pages/LoginPage/LoginPage.js
frontend/src/pages/LoginPage/LoginPage.test.js
frontend/src/pages/LoginPage/__snapshots__/LoginPage.test.js.snap

feat:loginpage

---

frontend/package.json
frontend/src/components/Intro/Introduction/Introduction.js
frontend/src/components/Waiting/WaitingSection/WaitingSection.js
frontend/src/components/Waiting/WaitingSection/WaitingSection.stories.js
frontend/src/components/Waiting/WaitingSection/WaitingSection.test.js
frontend/src/components/Waiting/WaitingSection/__snapshots__/WaitingSection.test.js.snap
frontend/src/components/Waiting/WaitingSection/index.js
frontend/src/containers/WaitingContainer/WaitingContainer.js
frontend/src/pages/WaitingPage/WaitingPage.js
frontend/src/pages/WaitingPage/__snapshots__/WaitingPage.test.js.snap
frontend/yarn.lock

feat: styling Waiting page component

---

backend/user_service/user/app/tests/test_user_application_service.py
backend/user_service/user/app/user_application_service.py

refactor: user_application_service login

---

frontend/src/containers/LoginContainer/LoginContainer.js
frontend/src/containers/RegisterContainer/RegisterForm.js
frontend/src/containers/RegisterContainer/__snapshots__/RegisterForm.test.js.snap

feat: implement loading feature for login and register

---

backend/carpool_request_service/carpool_request/app/carpool_request_application_service.py
frontend/src/App.js
frontend/src/components/DriverDetail/DriverDetail.js
frontend/src/components/DriverDetail/__snapshots__/DriverDetail.test.js.snap
frontend/src/components/DriverFinal/DriverFinal.js
frontend/src/components/DriverFinal/DriverFinal.test.js
frontend/src/components/DriverFinal/__snapshots__/DriverFinal.test.js.snap
frontend/src/components/RiderDetail/RiderDetail.js
frontend/src/components/RiderDetail/__snapshots__/RiderDetail.test.js.snap
frontend/src/components/RiderFinal/RiderFinal.js
frontend/src/components/RiderFinal/__snapshots__/RiderFinal.test.js.snap
frontend/src/containers/DriverDetailContainer/DriverDetailContainer.js
frontend/src/containers/DriverDetailContainer/__snapshots__/DriverDetailContainer.test.js.snap
frontend/src/containers/DriverFinalContainer/DriverFinalContainer.js
frontend/src/containers/RiderDetailContainer/__snapshots__/RiderDetailContainer.test.js.snap
frontend/src/lib/grpc/client.js
frontend/src/pages/DriverDetailPage/__snapshots__/DriverDetailPage.test.js.snap
frontend/src/pages/DriverFinalPage/__snapshots__/DriverFinalPage.test.js.snap
frontend/src/pages/RiderDetailPage/__snapshots__/RiderDetailPage.test.js.snap
frontend/src/pages/RiderFinalPage/RiderFinalPage.js

resolved #<issue-number> 
💔Thank you!

feat: detail, final component css

---

frontend/src/components/RequestCall/RequestCallSection/RequestCallSection.js
frontend/src/components/RequestCall/RequestCallSection/__snapshots__/RequestCallSection.test.js.snap
frontend/src/containers/DriverDetailContainer/DriverDetailContainer.js
frontend/src/containers/RequestCallContainer/RequestCallContainer.js
frontend/src/pages/RequestCallPage/__snapshots__/RequestCallPage.test.js.snap

resolved #<issue-number> 
💔Thank you!

feat: request call css

---

backend/user_service/user/app/user_application_service.py
frontend/src/components/DriverDetail/DriverDetail.js
frontend/src/components/DriverFinal/DriverFinal.js
frontend/src/components/DriverFinal/DriverFinal.test.js
frontend/src/components/RiderDetail/RiderDetail.js
frontend/src/components/RiderFinal/RiderFinal.js
frontend/src/containers/DriverFinalContainer/DriverFinalContainer.js
frontend/src/containers/LoginContainer/LoginContainer.js
frontend/src/containers/LoginContainer/LoginContainer.test.js
frontend/src/containers/RegisterContainer/RegisterForm.js
frontend/src/modules/auth/auth.js
frontend/src/pages/RiderFinalPage/RiderFinalPage.js

chore: fix loading error

---

frontend/src/types/location.js

 fix: dormitary pin location
